baseURL = "https://krizsx.github.io"
languageCode = "en-us"
title = "KrisX Blog"
# config
theme = "dream"
defaultContentLanguage = "en"
# googleAnalytics = "UA-167402242-1"
enableRobotsTXT=true
enableEmoji=true
# enableGitInfo=true
[params]
  # background = "black"
  backgroundImage = "/img/background.png"
  linkColor = "seagreen"
  author = "KrizsX"
  description = "个人博客"
  avatar = "/img/avator.jpeg"
  motto = "加一层可以解决所有问题"

  email = "cb.kris.bj@gmail.com"
  github = "krizsx"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # options
  showSummaryCoverInPost = false

  # dark mode
#   darkLinkColor = "darkseagreen"
  # darkNav = true
  dark404 = true